SELECT PRODUCT_CODE, SUM(SALES_AMOUNT) * PRICE as SALES
FROM OFFLINE_SALE JOIN PRODUCT
    ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY OFFLINE_SALE.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;